const dogCard = [
  {
    "id": 1,
    "category": "adopcion",
    "nombre": "Max",
    "descripcion": "Cachorro de raza mixta juguetón y amigable",
    "descripcionlarga": "Max fue encontrado en una fría noche de invierno en el parque central de la ciudad. Estaba solo y temblando, claramente perdido y desesperado por encontrar refugio. Sus patas estaban sucias y heridas debido a las largas caminatas en busca de comida. Su salud era precaria, con signos de desnutrición y debilidad. Max necesitaba ayuda urgentemente.\n\nDespués de ser rescatado por el refugio 'Amigos Peludos', Max recibió atención médica inmediata. Fue sometido a un tratamiento para tratar sus heridas y mejorar su salud. Pasó semanas recibiendo amor y cuidados incondicionales en el refugio. Con el tiempo, su confianza en las personas creció, y su naturaleza juguetona emergió. Hoy en día, Max es un perro lleno de energía y felicidad. Está completamente recuperado y listo para encontrar un hogar amoroso que le dé el cariño que merece.",
    "tamaño": "Pequeño",
    "sexo": "Macho",
    "edad": "Vacunado",
    "refugio": "Amigos Peludos",
    "imagen": "../content_edit/img/section3/carusel/dog1.png"
  },
  {
    "id": 2,
    "category": "adopcion",
    "nombre": "Bella",
    "descripcion": "Cachorra de raza labrador cariñosa y sociable",
    "descripcionlarga": "Bella fue rescatada de una situación de abandono en un parque cercano. Estaba sola y asustada, buscando desesperadamente comida. Su pelaje estaba sucio y enmarañado, y mostraba signos de desnutrición. Bella fue llevada al refugio 'Rescate Canino', donde recibió atención médica y cuidado amoroso. Con el tiempo, Bella se recuperó por completo y se convirtió en una perrita cariñosa y sociable. Ahora, disfruta jugando con otros perros y buscando el cariño de las personas.",
    "tamaño": "Grande",
    "sexo": "Hembra",
    "edad": "Vacunada",
    "refugio": "Rescate Canino",
    "imagen": "../content_edit/img/section3/carusel/dog2.png"
  },
  {
    "id": 3,
    "category": "adopcion",
    "nombre": "Rocky",
    "descripcion": "Perro adulto de raza pastor alemán protector",
    "descripcionlarga": "Rocky fue encontrado vagando solo por las calles, mostrando signos de abandono. Su pelaje estaba sucio y descuidado, y tenía algunas heridas leves. Se notaba que había tenido un pasado difícil. Después de ser llevado al refugio 'Amor y Patas', Rocky recibió atención médica y comenzó su proceso de recuperación. Ahora, es un perro protector y leal que se preocupa profundamente por su familia adoptiva. Disfruta de largos paseos y se asegura de que su hogar esté seguro en todo momento.",
    "tamaño": "Grande",
    "sexo": "Macho",
    "edad": "Vacunado",
    "refugio": "Amor y Patas",
    "imagen": "../content_edit/img/section3/carusel/dog3.png"
  },
  {
    "id": 4,
    "category": "adopcion",
    "nombre": "Daisy",
    "descripcion": "Cachorra de raza bulldog juguetona y leal",
    "descripcionlarga": "Daisy fue rescatada de una situación de abandono en un parque cercano. Estaba sola y asustada, buscando desesperadamente comida. Su pelaje estaba sucio y enmarañado, y mostraba signos de desnutrición. Daisy fue llevada al refugio 'Esperanza Animal', donde recibió atención médica y cuidado amoroso. Con el tiempo, Daisy se recuperó por completo y se convirtió en una perrita juguetona y leal. Ahora, disfruta de juegos activos y siempre está lista para hacer nuevos amigos.",
    "tamaño": "Mediano",
    "sexo": "Hembra",
    "edad": "Vacunada",
    "refugio": "Esperanza Animal",
    "imagen": "../content_edit/img/section3/carusel/dog4.png"
  },
  {
    "id": 5,
    "category": "adopcion",
    "nombre": "Buddy",
    "descripcion": "Perro adulto de raza golden retriever amigable y obediente",
    "descripcionlarga": "Buddy fue encontrado abandonado en un parque local, esperando en vano a su familia. Estaba en un estado de tristeza y desconfianza. Su salud también era un motivo de preocupación, con signos de desnutrición. Fue llevado al refugio 'Rescate Canino', donde recibió atención médica y apoyo emocional. Hoy en día, Buddy es un perro amigable y obediente que ama jugar con otros perros y hacer feliz a su familia adoptiva. Su lealtad es incomparable.",
    "tamaño": "Grande",
    "sexo": "Macho",
    "edad": "Vacunado",
    "refugio": "Rescate Canino",
    "imagen": "../content_edit/img/section3/carusel/dog5.png"
  },
  {
    "id": 6,
    "category": "adopcion",
    "nombre": "Lola",
    "descripcion": "Cachorra de raza pug curiosa y cariñosa",
    "descripcionlarga": "Lola fue encontrada en un parque, sola y buscando atención. Aunque su pelaje estaba en buen estado, se notaba que estaba asustada y necesitaba cuidados. Fue llevada al refugio 'Amigos Peludos', donde recibió amor y cuidado. Ahora, Lola es una cachorra curiosa y cariñosa que disfruta explorando su entorno y recibiendo mimos de las personas. Siempre está lista para hacer sonreír a quienes la rodean.",
    "tamaño": "Pequeño",
    "sexo": "Hembra",
    "edad": "Vacunada",
    "refugio": "Amigos Peludos",
    "imagen": "../content_edit/img/section3/carusel/dog6.png"
  },
  {
    "id": 7,
    "category": "adopcion",
    "nombre": "Rocky",
    "descripcion": "Cachorro de raza boxer enérgico y juguetón",
    "descripcionlarga": "Rocky fue encontrado en un parque local, corriendo y jugando sin dueño. Su energía era contagiosa, pero también evidenciaba su necesidad de atención y cuidado. Fue llevado al refugio 'Milagros Caninos', donde se le brindó cuidado y amor. Hoy en día, Rocky es un perro enérgico y juguetón que disfruta de la compañía de otros perros y de las actividades al aire libre. Es el compañero perfecto para una familia activa.",
    "tamaño": "Mediano",
    "sexo": "Macho",
    "edad": "Vacunado",
    "refugio": "Milagros Caninos",
    "imagen": "../content_edit/img/section3/carusel/dog7.png"
  },
  {
    "id": 8,
    "category": "adopcion",
    "nombre": "Lucy",
    "descripcion": "Cachorra de raza beagle traviesa y simpática",
    "descripcionlarga": "Lucy fue rescatada de un refugio superpoblado, donde estaba ansiosa por encontrar un hogar. A pesar de su tamaño pequeño, su personalidad traviesa y simpática la hacía destacar. Lucy fue llevada al refugio 'Esperanza Animal', donde recibió amor y cuidado. Ahora, Lucy es una cachorra traviesa y simpática que adora explorar y jugar con juguetes. Siempre está lista para compartir su alegría con su familia adoptiva.",
    "tamaño": "Pequeño",
    "sexo": "Hembra",
    "edad": "Vacunada",
    "refugio": "Esperanza Animal",
    "imagen": "../content_edit/img/section3/carusel/dog8.png"
  },
  {
    "id": 9,
    "category": "adopcion",
    "nombre": "Charlie",
    "descripcion": "Perro adulto de raza dálmata elegante y amigable",
    "descripcionlarga": "Charlie fue encontrado en un parque, vagando solo y buscando compañía. A pesar de su elegante pelaje de dálmata, se notaba que necesitaba atención. Fue llevado al refugio 'Amor y Patas', donde recibió cuidado y amor. Ahora, Charlie es un perro amigable y elegante que disfruta de largos paseos y de la compañía de las personas. Su naturaleza amigable lo convierte en un gran compañero para cualquier hogar.",
    "tamaño": "Mediano",
    "sexo": "Macho",
    "edad": "Vacunado",
    "refugio": "Amor y Patas",
    "imagen": "../content_edit/img/section3/carusel/dog9.png"
  },
  {
    "id": 10,
    "category": "adopcion",
    "nombre": "Lucy",
    "descripcion": "Cachorra de raza beagle traviesa y simpática",
    "descripcionlarga": "Lucy fue rescatada de un refugio superpoblado, donde estaba ansiosa por encontrar un hogar. A pesar de su tamaño pequeño, su personalidad traviesa y simpática la hacía destacar. Lucy fue llevada al refugio 'Esperanza Animal', donde recibió amor y cuidado. Ahora, Lucy es una cachorra traviesa y simpática que adora explorar y jugar con juguetes. Siempre está lista para compartir su alegría con su familia adoptiva.",
    "tamaño": "Pequeño",
    "sexo": "Hembra",
    "edad": "Vacunada",
    "refugio": "Esperanza Animal",
    "imagen": "../content_edit/img/section3/carusel/dog8.png"
  },
  {
    "id": 11,
    "category": "adopcion",
    "nombre": "Rocky",
    "descripcion": "Cachorro de raza boxer enérgico y juguetón",
    "descripcionlarga": "Rocky fue encontrado en un parque local, corriendo y jugando sin dueño. Su energía era contagiosa, pero también evidenciaba su necesidad de atención y cuidado. Fue llevado al refugio 'Milagros Caninos', donde se le brindó cuidado y amor. Hoy en día, Rocky es un perro enérgico y juguetón que disfruta de la compañía de otros perros y de las actividades al aire libre. Es el compañero perfecto para una familia activa.",
    "tamaño": "Mediano",
    "sexo": "Macho",
    "edad": "Vacunado",
    "refugio": "Milagros Caninos",
    "imagen": "../content_edit/img/section3/carusel/dog7.png"
  },
  {
    "id": 12,
    "category": "adopcion",
    "nombre": "Buddy",
    "descripcion": "Perro adulto de raza golden retriever amigable y obediente",
    "descripcionlarga": "Buddy fue encontrado abandonado en un parque local, esperando en vano a su familia. Estaba en un estado de tristeza y desconfianza. Su salud también era un motivo de preocupación, con signos de desnutrición. Fue llevado al refugio 'Rescate Canino', donde recibió atención médica y apoyo emocional. Hoy en día, Buddy es un perro amigable y obediente que ama jugar con otros perros y hacer feliz a su familia adoptiva. Su lealtad es incomparable.",
    "tamaño": "Grande",
    "sexo": "Macho",
    "edad": "Vacunado",
    "refugio": "Rescate Canino",
    "imagen": "../content_edit/img/section3/carusel/dog5.png"
  },
];